name: onDemand
on: 
  workflow_dispatch:
    inputs:
      maVar:
        description: 'ma variable'     
        required: true
        default: 'valeur par defaut'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install yq
      run: |
        # echo "ma variable: ${{ github.event.inputs.maVar }}"
        pip3 install yq
        ln -s /home/runner/.local/bin/yq /usr/local/bin
    - name: code exec
      run: |
        yq '.config.organisations.orga1.name' config.yml
        yq '.config.organisations.orga2.name' config.yml